#!/bin/sh

test -f /etc/astra/config.lua || exit 0

case "$1" in
  start)
    echo "Starting astra"
    ulimit -n 65536
    /usr/bin/astra --pid /var/run/astra.pid /etc/astra/config.lua &
    ;;
  stop)
    echo "Stopping astra"
    kill `cat /var/run/astra.pid`
    ;;
  restart|reload|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 1
esac

exit 0
